In [25]:
import pandas as pd
from pathlib import Path

In [26]:
dir_path = Path.cwd().resolve().parents[0]
data_folder = dir_path.joinpath("data")

# Load data
X_df = pd.read_parquet(data_folder.joinpath("X.parquet"))
y_df = pd.read_parquet(data_folder.joinpath("Y.parquet"))

In [27]:
y_df

       speciesID
0              4
1              8
2              9
3              5
4              2
...          ...
26199         10
26200          1
26201          0
26202          5
26203          7

[26204 rows x 1 columns]

In [28]:
X_df

,VV_VH_Ratio_2019_1,VV_VH_Ratio_2019_2,VV_VH_Ratio_2019_3,VV_VH_Ratio_2019_4,VV_VH_Ratio_2019_5,VV_VH_Ratio_2019_6,VV_VH_Ratio_2019_7,VV_VH_Ratio_2019_8,VV_VH_Ratio_2019_9,VV_VH_Ratio_2019_10,...,TCI_B_2021_3,TCI_B_2021_4,TCI_B_2021_5,TCI_B_2021_6,TCI_B_2021_7,TCI_B_2021_8,TCI_B_2021_9,TCI_B_2021_10,TCI_B_2021_11,TCI_B_2021_12
0,0.0000,0.0000,0.7153,0.6596,0.7209,0.6448,0.7872,0.6440,0.6619,0.4866,...,0.9787,0.7733,0.8397,0.7756,1.0,0.0,0.1932,0.7547,0.9375,0.3443
1,0.4210,0.8203,0.9781,0.9025,0.8758,0.8153,0.9703,0.8254,0.8060,0.8463,...,1.0000,0.8733,1.0000,1.0000,0.0,0.0,0.0000,1.0000,1.0000,0.3736
2,0.0384,0.4487,0.6527,0.0000,0.6864,0.0000,0.9008,0.0000,0.0000,0.2700,...,0.6702,0.5667,0.0000,0.0000,0.0,0.0,0.0000,0.4717,0.4732,0.0000
3,0.0384,0.4487,0.6527,0.0000,0.6864,0.0000,0.9008,0.0000,0.0000,0.2700,...,0.6702,0.5667,0.0000,0.0000,0.0,0.0,0.0000,0.4717,0.4732,0.0000
4,0.0000,0.0000,0.7153,0.6596,0.7209,0.6448,0.7872,0.6440,0.6619,0.4866,...,0.9787,0.7733,0.8397,0.7756,1.0,0.0,0.1932,0.7547,0.9375,0.3443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26199,0.5933,0.8028,0.9357,0.8816,0.8635,0.8588,0.9144,0.8368,0.8024,0.8428,...,0.8085,0.5267,0.6026,0.6795,0.0,1.0,1.0000,0.5755,0.6696,1.0000
26200,0.0384,0.4487,0.6527,0.0000,0.6864,0.0000,0.9008,0.0000,0.0000,0.2700,...,0.6702,0.5667,0.0000,0.0000,0.0,0.0,0.0000,0.4717,0.4732,0.0000
26201,0.0384,0.4487,0.6527,0.0000,0.6864,0.0000,0.9008,0.0000,0.0000,0.2700,...,0.6702,0.5667,0.0000,0.0000,0.0,0.0,0.0000,0.4717,0.4732,0.0000
26202,0.0384,0.4487,0.6527,0.0000,0.6864,0.0000,0.9008,0.0000,0.0000,0.2700,...,0.6702,0.5667,0.0000,0.0000,0.0,0.0,0.0000,0.4717,0.4732,0.0000
26203,0.0000,0.0000,0.7153,0.6596,0.7209,0.6448,0.7872,0.6440,0.6619,0.4866,...,0.9787,0.7733,0.8397,0.7756,1.0,0.0,0.1932,0.7547,0.9375,0.3443